### ISSUE TITLE
Developer Story | Portfolio

### ISSUE THREAD

**Issue by theachoem** [theachoem/portfolio-jekyll#9]

**Comment by theachoem** [comment]
![undraw_flutter_dev_wvqj](https://user-images.githubusercontent.com/29684683/132102769-97fb62ea-4fd9-4a12-9a1e-7f2fe3a03d35.png)

**Comment by theachoem** [comment]
Look great!

**Comment by VatanakChamroeun** [comment]
Hello

**Comment by theachoem** [comment]
I could say my life changing event is on vacation term 3 during COVID 19 (August 2020). My plans: https://github.com/vacation-term3/READ-ME

**Comment by theachoem** [comment]
What I do at Erobot?
I build the Mobile team from the ground up. We share knowledge, make free courses for juniors, help develop applications for controlling robots, showcase & inspiring next generation.
